### ISSUE TITLE
how to run this?

### ISSUE THREAD

**Issue by forerser** [darealshinji/aegisub-appimage#1]
Hi, can you explain how to do this please, or can you release an appimage?

**Comment by darealshinji** [comment]
You can find a prebuilt AppImage in the [release section](https://github.com/darealshinji/aegisub-appimage/releases).
Here's a direct link to it: [aegisub-9232-dev-33ff9b408.AppImage](https://github.com/darealshinji/aegisub-appimage/releases/download/9232-dev-33ff9b408/aegisub-9232-dev-33ff9b408.AppImage)
Just download it, make it executable and launch it.

**Comment by forerser** [comment]
oh, didn't notice that, appreciate it. Thank you.
